apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 3ta-vks
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/KBrookfield/argocd'
    targetRevision: main
    path: 3ta/apps/3ta-vks/manifests
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  # Runs in parallel with 3ta-vm
  syncWave: -1