apiVersion: batch/v1
kind: Job
metadata:
  name: register-vks-01
  namespace: argocd
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
      - name: register
        image: ""  # Runs in-cluster without pulling an image
        command: ["/bin/sh", "-c"]
        args:
          - |
            echo "Waiting for kubeconfig to be available..."
            while ! kubectl get secret vks-01-kubeconfig -n argocd -o jsonpath='{.data.value}' | base64 -d > /tmp/vks-01-kubeconfig; do
              sleep 5
            done

            echo "Extracting correct context..."
            CONTEXT=$(kubectl config --kubeconfig=/tmp/vks-01-kubeconfig view -o jsonpath='{.contexts[0].name}')

            echo "Registering vks-01 in ArgoCD with context: $CONTEXT"
            argocd cluster add $CONTEXT --kubeconfig /tmp/vks-01-kubeconfig

            echo "Triggering 3ta-app deployment..."
            kubectl annotate app 3ta-app argocd.argoproj.io/sync-wave="1" -n argocd
      restartPolicy: Never
