apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 3ta-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/KBrookfield/argocd'
    targetRevision: main
    path: 3ta/apps/3ta-app
  destination:
    # This is critical: you want to deploy to the newly registered cluster
    # Use the cluster context name that Argo CD sees after registration
    name: 'vks-01-admin@vks-01'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  # Deploy after the cluster is registered
  syncWave: 2